#!/bin/bash

set -e -o pipefail

MODULE=$(go list -m)

# Ensure the protobufs are present before
# running go mod tidy.
make

rm -f go.mod go.sum
go mod init $MODULE
go mod tidy
bun update

make nuke
